# Generated by Django 3.2.9 on 2021-11-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=25)),
                ('lastname', models.CharField(max_length=25)),
                ('cellNumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
