# Generated by Django 3.2.9 on 2021-11-27 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_client_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
